data_cfg:
  dataset_name: GREW
  dataset_root: /home/data/grew-pkl-fixed
  dataset_partition: ./datasets/GREW/GREW.json
  num_workers: 16
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: GREW

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 250000
  save_name: Baseline
  eval_func: GREW_submission # identification_real_scene # identification_GREW_submission
  sampler:
    batch_shuffle: false
    batch_size: 64
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform
      img_w: 64

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 0.1
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: Baseline
  backbone_cfg:
    in_channels: 1
    layers_cfg: # Layers configuration for automatically model construction
      - BC-32
      - BC-32
      - M
      - BC-64
      - BC-64
      - M
      - BC-128
      - BC-128
      - BC-256
      - BC-256
      # - M
      # - BC-512
      # - BC-512
    type: Plain
  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 20000
    in_channels: 256
    parts_num: 16
  bin_num:
    - 16
    # - 8
    # - 4
    # - 2
    # - 1

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 150000
  scheduler: MultiStepLR
trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: Baseline
  sync_BN: true
  total_iter: 250000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32 # TripletSampler, batch_size[0] indicates Number of Identity
      - 8 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 25 # min frames number for unfixed traing
    sample_type: fixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: BaseSilCuttingTransform
      img_w: 64
